"""Emit the golden fixture pack as JSON.

Every expected value in this file is a hand-computed literal. Nothing here calls the
engine. That is the whole point: a fixture generated by the engine it grades proves only
that the engine is self-consistent.

The arithmetic behind each number is written out in the comment above it so a reader can
check it without running anything. The standing test instrument keeps the arithmetic
trivial:

    tick 0.01, qty step 0.001, taker 0.001 (0.1%), maker 0.0004 (0.04%), qty 1.0,
    entry fill 100.00, starting equity 10 000, 1-minute bars,
    bar 0 ts 0, bar 1 ts 60 000, bar 2 ts 120 000, bar 3 ts 180 000.

Isolated liquidation for a long solves ``equity(P) == maintenance_margin(P)``:

    P_liq = (qty*entry - margin - deduction) / (qty * (1 - mm_rate - close_fee_rate))

At leverage 10 the margin is 10, so P_liq = (100 - 10) / (1 - 0.005 - 0.001)
                                          = 90 / 0.994 = 90.5432...  -> 90.55 (ceil to tick, adverse).
At leverage 50 the margin is 2,  so P_liq = 98 / 0.994 = 98.5915...  -> 98.60.
At leverage  2 the margin is 50, so P_liq = 50 / 0.994 = 50.3018...  -> 50.31.

Run with:  python tools/build_fixtures.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

OUT_DIR = Path(__file__).resolve().parent.parent / "src" / "tradesim" / "conformance" / "fixtures"

TF = 60_000  # one-minute bars

INSTRUMENT: dict[str, Any] = {
    "symbol": "TESTUSDT",
    "tick_size": 0.01,
    "qty_step": 0.001,
    "min_qty": 0.001,
    "min_notional": 1.0,
    "max_leverage": 100.0,
    "maintenance_rate": 0.005,
    "funding_interval_ms": 28_800_000,
}

COSTS: dict[str, Any] = {
    "taker_rate": 0.001,
    "maker_rate": 0.0004,
    "entry_slippage": 0.0,
    "market_exit_slippage": 0.0,
    "spread": 0.0,
}

MARGIN_L10: dict[str, Any] = {
    "mode": "isolated",
    "leverage": 10.0,
    "maintenance_buffer": 0.005,
    "mark_buffer": 0.002,
    "include_close_fee_in_liquidation": True,
    "require_stop_inside_liquidation": True,
}

SIZING_Q1: dict[str, Any] = {"mode": "fixed_qty", "fixed_qty": 1.0}

SIM: dict[str, Any] = {
    "entry_ref": "next_open",
    "same_bar_policy": "adverse",
    "max_hold_bars": None,
    "starting_equity": 10_000.0,
    "close_at_end_of_data": True,
    "decision_timeframe": "1m",
}

QUIET_SIGNAL_BAR = [0, 100.0, 100.0, 100.0, 100.0]
QUIET_BAR_1 = [TF, 100.0, 101.0, 99.0, 100.0]


def fixture(
    ids: list[str],
    title: str,
    *,
    bars: list[list[float]],
    signals: list[dict[str, Any]],
    expect: dict[str, Any],
    instrument: dict[str, Any] | None = None,
    costs: dict[str, Any] | None = None,
    margin: dict[str, Any] | None = None,
    sizing: dict[str, Any] | None = None,
    sim: dict[str, Any] | None = None,
    touch_bars: dict[str, Any] | None = None,
    funding: list[list[float]] | None = None,
    kind: str = "simulation",
    rationale: str = "",
) -> dict[str, Any]:
    return {
        "ids": ids,
        "kind": kind,
        "title": title,
        "rationale": rationale,
        "instrument": {**INSTRUMENT, **(instrument or {})},
        "costs": {**COSTS, **(costs or {})},
        "margin": {**MARGIN_L10, **(margin or {})},
        "sizing": {**SIZING_Q1, **(sizing or {})},
        "sim": {**SIM, **(sim or {})},
        "bars": {"timeframe_ms": TF, "rows": bars},
        "touch_bars": touch_bars,
        "funding": funding or [],
        "signals": signals,
        "expect": expect,
        "tolerance": 1e-9,
    }


LONG_95_110 = {"ts_ms": 0, "side": 1, "stop_price": 95.0, "target_price": 110.0}


def build() -> dict[str, dict[str, Any]]:
    f: dict[str, dict[str, Any]] = {}

    # ================================================================== EXEC-001 ======
    # Signal is known at bar 0's close (100.00). Bar 0's range is 80..120 and would have
    # taken out a stop at 95 twice over. A conformant engine never sees that range: it
    # fills at bar 1's open of 102.00 and only bar 1 onward is post-entry.
    #   entry fee = 1 * 102.00 * 0.001 = 0.102
    #   exit  fee = 1 * 110.00 * 0.001 = 0.110
    #   gross     = 110 - 102 = 8.00
    #   realized  = 8.00 - 0.102 - 0.110 = 7.788
    f["EXEC-001_no_retroactive_close_fill"] = fixture(
        ["EXEC-001", "CAUS-001"],
        "A close-based signal fills at the next open, and the signal bar's range is not post-entry",
        rationale=(
            "Bar 0 spans 80..120. An engine that fills at bar 0's close and then scans "
            "bar 0 would report a stop-out at 95 on bar 0. The correct answer is a "
            "target at 110 on bar 2, entered at 102.00 on bar 1."
        ),
        bars=[
            [0, 100.0, 120.0, 80.0, 100.0],
            [TF, 102.0, 103.0, 101.0, 102.0],
            [2 * TF, 102.0, 112.0, 101.0, 111.0],
        ],
        signals=[LONG_95_110],
        margin={"leverage": 2.0},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "entry_ref_price": 102.0,
                    "entry_price": 102.0,
                    "exit_ts_ms": 2 * TF,
                    "exit_price": 110.0,
                    "exit_reason": "target",
                    "entry_fee": 0.102,
                    "exit_fee": 0.11,
                    "gross_pnl": 8.0,
                    "realized_pnl": 7.788,
                    "hold_bars": 1,
                    "entry_bar_exit": False,
                }
            ],
            "ending_equity": 10007.788,
        },
    )

    # ================================================================== EXEC-002 ======
    # entry slippage 0.001 moves the PRICE: 100.00 * 1.001 = 100.10 (already on tick).
    #   entry fee = 1 * 100.10 * 0.001 = 0.1001   <- rate applied to the SLIPPED price
    #   a wrong engine folding slip into the rate would charge 100 * 0.002 = 0.20
    #   exit at the 110 limit, fee = 0.110, gross = 110 - 100.10 = 9.90
    #   realized = 9.90 - 0.1001 - 0.110 = 9.6899
    f["EXEC-002_entry_slippage_moves_price"] = fixture(
        ["EXEC-002"],
        "Entry slippage moves the fill price; the fee rate is untouched",
        rationale="Fee must be 0.1001 (rate on the slipped price), never 0.2 (rate plus slip).",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 112.0, 99.0, 111.0],
        ],
        signals=[LONG_95_110],
        costs={"entry_slippage": 0.001},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ref_price": 100.0,
                    "entry_price": 100.1,
                    "entry_fee": 0.1001,
                    "exit_price": 110.0,
                    "exit_fee": 0.11,
                    "gross_pnl": 9.9,
                    "realized_pnl": 9.6899,
                    "slippage_cost": 0.1,
                }
            ],
        },
    )

    # ================================================================== EXEC-003 ======
    # Entry is a market taker fill; the take profit rests as a maker limit.
    #   entry fee = 1 * 100 * 0.001  = 0.1000  at the taker rate
    #   exit  fee = 1 * 110 * 0.0004 = 0.0440  at the maker rate
    #   realized  = 10 - 0.1 - 0.044 = 9.856
    f["EXEC-003_fee_per_fill_maker_taker"] = fixture(
        ["EXEC-003"],
        "Fee is charged per fill at that fill's own maker or taker rate",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 112.0, 99.0, 111.0],
        ],
        signals=[LONG_95_110],
        costs={"role_liquidity": {"entry": "taker", "take_profit": "maker"}},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_fee": 0.1,
                    "exit_fee": 0.044,
                    "fees": 0.144,
                    "realized_pnl": 9.856,
                }
            ],
            "fill_rates": [0.001, 0.0004],
        },
    )

    # ================================================================== EXEC-004 ======
    # Bar 2 opens at 90.00, already through the stop at 95.00. A stop-market cannot fill
    # at 95: it fills at the first available price, the open.
    #   exit fee = 1 * 90 * 0.001 = 0.09
    #   gross = 90 - 100 = -10.00, realized = -10 - 0.1 - 0.09 = -10.19
    # Leverage 2 keeps the liquidation at 50.31, well clear of the gap.
    f["EXEC-004_gap_through_stop"] = fixture(
        ["EXEC-004"],
        "A gap through a stop-MARKET fills worse than the stop",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 90.0, 91.0, 88.0, 89.0],
        ],
        signals=[LONG_95_110],
        margin={"leverage": 2.0},
        # Explicit: this identifier grades stop-market gap behaviour, not the project
        # default (stop-limit at the level).
        sim={"stop_is_stop_market": True},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 90.0,
                    "exit_reason": "stop",
                    "exit_fee": 0.09,
                    "gross_pnl": -10.0,
                    "realized_pnl": -10.19,
                }
            ],
        },
    )

    # ================================================================== EXEC-005 ======
    # Bar 2 gaps straight past the 110 target to open at 115. A resting limit order does
    # not get a better price handed to it in this model, and it does not slip:
    # the fill is exactly 110.00 even though market exit slippage is configured at 0.002.
    #   exit fee = 0.110, gross = 10.00, realized = 10 - 0.1 - 0.11 = 9.79
    f["EXEC-005_tp_limit_no_favourable_slip"] = fixture(
        ["EXEC-005"],
        "A take-profit limit fills at the limit price with no favourable slippage",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 115.0, 116.0, 114.0, 115.0],
        ],
        signals=[LONG_95_110],
        costs={"market_exit_slippage": 0.002},
        sim={"take_profit_is_limit": True},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 110.0,
                    "exit_reason": "target",
                    "exit_fee": 0.11,
                    "realized_pnl": 9.79,
                    "slippage_cost": 0.0,
                }
            ],
        },
    )

    # Market-triggered take profit on the same bars: the trigger fires at 110 and the
    # market fill slips adversely. A favourable gap never improves the fill.
    #   fill = 110 * (1 - 0.002) = 109.78
    #   exit fee = 109.78 * 0.001 = 0.10978
    #   gross = 9.78, realized = 9.78 - 0.1 - 0.10978 = 9.57022
    f["EXEC-005_tp_market_does_slip"] = fixture(
        ["EXEC-005"],
        "A market-triggered take profit does incur exit slippage",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 115.0, 116.0, 114.0, 115.0],
        ],
        signals=[LONG_95_110],
        costs={"market_exit_slippage": 0.002},
        sim={"take_profit_is_limit": False},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 109.78,
                    "exit_reason": "target",
                    "exit_fee": 0.10978,
                    "realized_pnl": 9.57022,
                }
            ],
        },
    )

    # ================================================================== EXEC-006 ======
    # Bar 2 spans 94..111, containing both the 95 stop and the 110 target. With no
    # lower-timeframe data the adverse branch is taken and the trade is labelled
    # ambiguous. Same arithmetic as a plain stop: realized = -5 - 0.1 - 0.095 = -5.195.
    f["EXEC-006_both_in_bar_adverse"] = fixture(
        ["EXEC-006"],
        "Stop and target in one bar resolves adversely and is labelled ambiguous",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 100.0, 111.0, 94.0, 100.0],
        ],
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 95.0,
                    "exit_reason": "stop",
                    "realized_pnl": -5.195,
                    "ambiguous": True,
                    "resolved_by_touch": False,
                }
            ],
            "summary": {"ambiguous_intrabar": 1},
        },
    )

    # The same decision bar, now with 15-second touch bars showing the target was reached
    # first. The ambiguity is resolved by data, not by policy: target at 110, not
    # ambiguous, and flagged as touch-resolved.
    #   realized = 10 - 0.1 - 0.11 = 9.79
    f["EXEC-006_both_in_bar_touch_resolved"] = fixture(
        ["EXEC-006", "CAUS-004"],
        "Lower-timeframe replay resolves a dual touch instead of falling back to adverse",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 100.0, 111.0, 94.0, 100.0],
        ],
        touch_bars={
            "timeframe_ms": 15_000,
            "rows": [
                [TF + 0, 100.0, 100.5, 99.0, 100.0],
                [TF + 15_000, 100.0, 101.0, 99.5, 100.5],
                [TF + 30_000, 100.5, 101.0, 100.0, 100.5],
                [TF + 45_000, 100.5, 101.0, 100.0, 100.0],
                [2 * TF + 0, 100.0, 111.0, 100.0, 110.5],
                [2 * TF + 15_000, 110.5, 111.0, 94.0, 95.0],
                [2 * TF + 30_000, 95.0, 96.0, 94.0, 95.0],
                [2 * TF + 45_000, 95.0, 101.0, 94.5, 100.0],
            ],
        },
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 110.0,
                    "exit_reason": "target",
                    "realized_pnl": 9.79,
                    "ambiguous": False,
                    "resolved_by_touch": True,
                    "exit_ts_ms": 2 * TF,
                }
            ],
        },
    )

    # ============================================================ EXEC-007 / QTY-007 ==
    # Continuous path. Entry 100, stop 95, liquidation 90.55 at leverage 10. Bar 2 runs
    # 100 -> 85 without gapping, so 95 is necessarily reached before 90.55: the stop
    # fires, not the liquidation. realized = -5 - 0.1 - 0.095 = -5.195.
    f["EXEC-007_stop_before_liquidation_continuous"] = fixture(
        ["EXEC-007", "QTY-007"],
        "On a continuous path the shallower stop is reached before the deeper liquidation",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 100.0, 100.0, 85.0, 86.0],
        ],
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 95.0,
                    "exit_reason": "stop",
                    "realized_pnl": -5.195,
                    "liquidation_price": 90.55,
                }
            ],
            "liquidation_status": "SIMPLIFIED",
        },
    )

    # A gap reverses that order. Leverage 2 puts the liquidation at 50.31 and the stop at
    # 60. Bar 2 opens at 50.00, below both, so the position is already liquidated when
    # trading resumes; the stop never gets its turn.
    #   fill = min(open, liq) = 50.00
    #   exit fee = 50 * 0.001 = 0.05
    #   gross = -50.00, realized = -50 - 0.1 - 0.05 = -50.15
    # The isolated margin was 50, so the modelled loss slightly exceeds it: the engine
    # must warn rather than quietly cap the loss in the trader's favour.
    f["QTY-007_gap_reverses_stop_liquidation_order"] = fixture(
        ["QTY-007", "EXEC-007"],
        "A gap can put liquidation ahead of the stop, and the engine says so",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 50.0, 51.0, 48.0, 49.0],
        ],
        signals=[{"ts_ms": 0, "side": 1, "stop_price": 60.0, "target_price": 110.0}],
        margin={"leverage": 2.0},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 50.0,
                    "exit_reason": "liquidation",
                    "liquidation_price": 50.31,
                    "realized_pnl": -50.15,
                }
            ],
            "warns_contains": "exceeds isolated margin",
        },
    )

    # ============================================================ EXEC-008 / EXEC-016 =
    # max_hold_bars = 2, entry on bar 1. Two bars later is bar 3, and the hold expires at
    # that bar's boundary, so the market order fills at bar 3's OPEN of 100.50.
    #   hold_bars = 3 - 1 = 2
    #   exit fee = 100.50 * 0.001 = 0.1005
    #   gross = 0.50, realized = 0.5 - 0.1 - 0.1005 = 0.2995
    f["EXEC-008_max_hold_exits_at_open_of_nth_bar"] = fixture(
        ["EXEC-008", "EXEC-016"],
        "Maximum hold exits at the open of entry_bar + max_hold_bars, counted from the entry bar",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 100.0, 101.0, 99.0, 100.5],
            [3 * TF, 100.5, 101.0, 99.5, 100.0],
            [4 * TF, 100.0, 101.0, 99.0, 100.0],
        ],
        signals=[LONG_95_110],
        sim={"max_hold_bars": 2},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": 3 * TF,
                    "exit_price": 100.5,
                    "exit_reason": "max_hold",
                    "hold_bars": 2,
                    "exit_fee": 0.1005,
                    "realized_pnl": 0.2995,
                }
            ],
        },
    )

    # ================================================================== EXEC-010 ======
    # THE headline case. Entry fills at bar 1's open of 100.00 and bar 1's own low of
    # 94.00 takes out the 95.00 stop. The trade must close on its entry bar.
    #   exit_ts == entry_ts == 60000, hold_bars == 0
    #   entry fee 0.100 + exit fee 0.095 are BOTH charged
    #   gross = -5.00, realized = -5 - 0.1 - 0.095 = -5.195
    #   ending equity = 10000 - 5.195 = 9994.805
    # Bar 1's low of 94.00 stays above the 90.55 liquidation, so the stop is the answer.
    f["EXEC-010_entry_bar_stop"] = fixture(
        ["EXEC-010"],
        "The entry bar's own range takes out the stop and the trade closes on its entry bar",
        rationale=(
            "This is the defect that moved a stitched out-of-sample profit factor from "
            "1.50 to 0.90. An engine that starts exit checking on the next bar reports "
            "no trade here, or a trade that survives."
        ),
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 94.0, 99.0],
            [2 * TF, 99.0, 100.0, 98.0, 99.0],
        ],
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": TF,
                    "entry_price": 100.0,
                    "exit_price": 95.0,
                    "exit_reason": "stop_entry_bar",
                    "entry_fee": 0.1,
                    "exit_fee": 0.095,
                    "fees": 0.195,
                    "gross_pnl": -5.0,
                    "realized_pnl": -5.195,
                    "hold_bars": 0,
                    "entry_bar_exit": True,
                }
            ],
            "ending_equity": 9994.805,
            "summary": {"entry_bar_exits": 1},
        },
    )

    # A short mirror of the same case: entry at 100, stop at 105, bar 1 high 106.
    #   exit fee = 105 * 0.001 = 0.105
    #   gross = (100 - 105) * 1 = -5.00, realized = -5 - 0.1 - 0.105 = -5.205
    f["EXEC-010_entry_bar_stop_short"] = fixture(
        ["EXEC-010"],
        "Entry-bar stop for a short position",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 106.0, 99.0, 101.0],
            [2 * TF, 101.0, 102.0, 100.0, 101.0],
        ],
        signals=[{"ts_ms": 0, "side": -1, "stop_price": 105.0, "target_price": 90.0}],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "side": -1,
                    "entry_ts_ms": TF,
                    "exit_ts_ms": TF,
                    "exit_price": 105.0,
                    "exit_reason": "stop_entry_bar",
                    "gross_pnl": -5.0,
                    "realized_pnl": -5.205,
                    "hold_bars": 0,
                    "entry_bar_exit": True,
                }
            ],
        },
    )

    # ================================================================== EXEC-011 ======
    # Bar 1's high of 111 reaches the 110 target on the entry bar.
    #   exit fee = 110 * 0.001 = 0.11
    #   gross = +10.00, realized = 10 - 0.1 - 0.11 = 9.79
    f["EXEC-011_entry_bar_target"] = fixture(
        ["EXEC-011"],
        "The entry bar's own range reaches the target and the trade closes on its entry bar",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 111.0, 99.0, 110.0],
            [2 * TF, 110.0, 111.0, 109.0, 110.0],
        ],
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": TF,
                    "exit_price": 110.0,
                    "exit_reason": "target_entry_bar",
                    "entry_fee": 0.1,
                    "exit_fee": 0.11,
                    "gross_pnl": 10.0,
                    "realized_pnl": 9.79,
                    "hold_bars": 0,
                    "entry_bar_exit": True,
                }
            ],
            "ending_equity": 10009.79,
        },
    )

    # ================================================================== EXEC-012 ======
    # Bar 1 spans 94..111: the entry bar contains both the stop and the target. Adverse
    # resolution takes the stop and marks the trade ambiguous.
    #   realized = -5 - 0.1 - 0.095 = -5.195
    f["EXEC-012_entry_bar_both_adverse"] = fixture(
        ["EXEC-012"],
        "The entry bar contains stop and target; the adverse one is taken and labelled ambiguous",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 111.0, 94.0, 100.0],
            [2 * TF, 100.0, 101.0, 99.0, 100.0],
        ],
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": TF,
                    "exit_price": 95.0,
                    "exit_reason": "stop_entry_bar",
                    "realized_pnl": -5.195,
                    "hold_bars": 0,
                    "ambiguous": True,
                    "entry_bar_exit": True,
                }
            ],
            "summary": {"ambiguous_intrabar": 1, "entry_bar_exits": 1},
        },
    )

    # The same entry bar with 15-second touch data proving the target came first.
    #   realized = 10 - 0.1 - 0.11 = 9.79, not ambiguous, touch-resolved, still hold 0.
    f["EXEC-012_entry_bar_both_touch_resolved"] = fixture(
        ["EXEC-012"],
        "Lower-timeframe data resolves an ambiguous entry bar",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 111.0, 94.0, 100.0],
            [2 * TF, 100.0, 101.0, 99.0, 100.0],
        ],
        touch_bars={
            "timeframe_ms": 15_000,
            "rows": [
                [0, 100.0, 100.0, 100.0, 100.0],
                [15_000, 100.0, 100.0, 100.0, 100.0],
                [30_000, 100.0, 100.0, 100.0, 100.0],
                [45_000, 100.0, 100.0, 100.0, 100.0],
                [TF + 0, 100.0, 111.0, 100.0, 110.5],
                [TF + 15_000, 110.5, 111.0, 94.0, 95.0],
                [TF + 30_000, 95.0, 96.0, 94.0, 95.0],
                [TF + 45_000, 95.0, 101.0, 94.5, 100.0],
                [2 * TF + 0, 100.0, 101.0, 99.0, 100.0],
                [2 * TF + 15_000, 100.0, 101.0, 99.0, 100.0],
                [2 * TF + 30_000, 100.0, 101.0, 99.0, 100.0],
                [2 * TF + 45_000, 100.0, 101.0, 99.0, 100.0],
            ],
        },
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": TF,
                    "exit_price": 110.0,
                    "exit_reason": "target_entry_bar",
                    "realized_pnl": 9.79,
                    "hold_bars": 0,
                    "ambiguous": False,
                    "resolved_by_touch": True,
                    "entry_bar_exit": True,
                }
            ],
        },
    )

    # ================================================================== EXEC-013 ======
    # Leverage 50 puts the liquidation at 98.60, nearer to the entry than the 90.00 stop.
    # Bar 1 runs down to 89.00, so on a continuous path liquidation is reached first and
    # it must resolve on the entry bar.
    #   exit fee = 98.60 * 0.001 = 0.0986
    #   gross = 98.60 - 100 = -1.40
    #   realized = -1.40 - 0.1 - 0.0986 = -1.5986
    # require_stop_inside_liquidation is switched off precisely so this ordering can be
    # observed; with it on, the order is rejected instead, which QTY-010 covers.
    f["EXEC-013_entry_bar_liquidation"] = fixture(
        ["EXEC-013"],
        "The entry bar reaches the liquidation price and liquidation resolves on the entry bar",
        rationale=(
            "The stop at 90.00 sits beyond the 98.60 liquidation, so the correct order "
            "is liquidation first. An engine that only checks the stop reports a much "
            "smaller loss, and one that skips the entry bar reports no exit at all."
        ),
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.5, 89.0, 90.0],
            [2 * TF, 90.0, 91.0, 89.0, 90.0],
        ],
        signals=[{"ts_ms": 0, "side": 1, "stop_price": 90.0, "target_price": 110.0}],
        margin={"leverage": 50.0, "require_stop_inside_liquidation": False},
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": TF,
                    "exit_price": 98.6,
                    "exit_reason": "liquidation_entry_bar",
                    "liquidation_price": 98.6,
                    "entry_fee": 0.1,
                    "exit_fee": 0.0986,
                    "gross_pnl": -1.4,
                    "realized_pnl": -1.5986,
                    "hold_bars": 0,
                    "entry_bar_exit": True,
                }
            ],
            "liquidation_status": "SIMPLIFIED",
        },
    )

    # ================================================================== EXEC-014 ======
    # THE NEGATIVE CONTROL. Bar 1 spans 99..101 and touches neither the 95 stop nor the
    # 110 target, so the position must survive its entry bar. Bar 2 then takes the stop.
    #   exit_ts = 120000 != entry_ts = 60000, hold_bars = 1
    #   exit_reason is plain "stop" with no _entry_bar suffix
    #   realized = -5 - 0.1 - 0.095 = -5.195
    # Without this fixture an engine passes EXEC-010 by closing every position instantly.
    f["EXEC-014_quiet_entry_bar_negative_control"] = fixture(
        ["EXEC-014"],
        "A quiet entry bar does NOT close the position and a later bar still resolves it",
        rationale=(
            "Paired control for EXEC-010. An engine that closes everything on the entry "
            "bar passes EXEC-010 and fails here."
        ),
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.5],
            [2 * TF, 100.5, 101.0, 94.0, 95.0],
            [3 * TF, 95.0, 96.0, 94.0, 95.0],
        ],
        signals=[LONG_95_110],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": 2 * TF,
                    "exit_price": 95.0,
                    "exit_reason": "stop",
                    "hold_bars": 1,
                    "realized_pnl": -5.195,
                    "entry_bar_exit": False,
                }
            ],
            "summary": {"entry_bar_exits": 0},
        },
    )

    # ================================================================== EXEC-015 ======
    # A funding settlement lands at 60000, exactly the entry timestamp, and another at
    # 120000, exactly the end of the entry bar. The position opens and closes inside bar
    # 1, so its holding window is [60000, 120000).
    #   settlement 60000: charged.  mark = bar 1's open = 100.00
    #     cashflow = -side * qty * mark * rate = -1 * 1 * 100 * 0.001 = -0.10
    #   settlement 120000: NOT charged, the window is exclusive at its end.
    #   realized = gross - fees + funding = -5 - 0.195 - 0.10 = -5.295
    f["EXEC-015_entry_bar_funding"] = fixture(
        ["EXEC-015", "FUND-005"],
        "A same-bar round trip is still charged the funding settlements inside its holding window",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 94.0, 99.0],
            [2 * TF, 99.0, 100.0, 98.0, 99.0],
        ],
        signals=[LONG_95_110],
        funding=[[TF, 0.001], [2 * TF, 0.002]],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "entry_ts_ms": TF,
                    "exit_ts_ms": TF,
                    "exit_reason": "stop_entry_bar",
                    "funding": -0.1,
                    "gross_pnl": -5.0,
                    "fees": 0.195,
                    "realized_pnl": -5.295,
                    "hold_bars": 0,
                }
            ],
            "n_funding_charges": 1,
        },
    )

    # ================================================================== EXEC-016 ======
    # Hold count for a same-bar exit is zero, not one.
    f["EXEC-016_same_bar_hold_is_zero"] = fixture(
        ["EXEC-016"],
        "A trade closed on its entry bar reports a hold of zero",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 111.0, 99.0, 110.0],
            [2 * TF, 110.0, 111.0, 109.0, 110.0],
        ],
        signals=[LONG_95_110],
        sim={"max_hold_bars": 5},
        expect={
            "n_trades": 1,
            "trades": [{"hold_bars": 0, "exit_reason": "target_entry_bar"}],
        },
    )

    # ================================================================== EXEC-018 ======
    # Two take-profit legs of 0.5 each, at 105 and 110, from a 1.0 entry at 100.
    #   entry fee = 1.0 * 100 * 0.001 = 0.1000
    #   leg 1 fee = 0.5 * 105 * 0.001 = 0.0525   filled on bar 2
    #   leg 2 fee = 0.5 * 110 * 0.001 = 0.0550   filled on bar 3
    #   gross = 0.5*(105-100) + 0.5*(110-100) = 2.50 + 5.00 = 7.50
    #   realized = 7.5 - 0.1 - 0.0525 - 0.055 = 7.2925
    #   volume-weighted exit price = (0.5*105 + 0.5*110) / 1.0 = 107.50
    f["EXEC-018_multi_leg_take_profit"] = fixture(
        ["EXEC-018"],
        "Each take-profit leg fills at its own price and quantity, and the residual closes",
        bars=[
            QUIET_SIGNAL_BAR,
            QUIET_BAR_1,
            [2 * TF, 100.0, 106.0, 99.0, 105.0],
            [3 * TF, 105.0, 111.0, 104.0, 110.0],
        ],
        signals=[
            {
                "ts_ms": 0,
                "side": 1,
                "stop_price": 95.0,
                "tp_legs": [
                    {"qty_fraction": 0.5, "price": 105.0, "label": "tp1"},
                    {"qty_fraction": 0.5, "price": 110.0, "label": "tp2"},
                ],
            }
        ],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "qty": 1.0,
                    "exit_ts_ms": 3 * TF,
                    "exit_price": 107.5,
                    "exit_reason": "target",
                    "fees": 0.2075,
                    "gross_pnl": 7.5,
                    "realized_pnl": 7.2925,
                    "n_legs": 2,
                }
            ],
        },
    )

    # ========================================================= EXEC-019 / CAUS-005 ====
    # Trailing stop 2% behind the running high, starting from a 95 hard stop.
    #   after bar 1 (high 100.00): stop = max(95, 100.00*0.98) = 98.00
    #   bar 2 low is 99.00, above 98.00 -> NO exit. An engine that applied bar 2's own
    #     high of 105 first would be trailing at 102.90 and would wrongly exit here.
    #   after bar 2 (high 105.00): stop = max(98, 105*0.98) = 102.90
    #   bar 3 low is 102.00 -> the trailing stop fires at 102.90
    #   exit fee = 102.90 * 0.001 = 0.1029
    #   gross = 2.90, realized = 2.9 - 0.1 - 0.1029 = 2.6971
    f["EXEC-019_trailing_stop_ratchet"] = fixture(
        ["EXEC-019", "CAUS-005"],
        "A trailing stop ratchets only upward and never uses the extreme of the bar it is resolving",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 105.0, 99.0, 104.0],
            [3 * TF, 104.0, 104.0, 102.0, 102.5],
        ],
        signals=[
            {
                "ts_ms": 0,
                "side": 1,
                "stop_price": 95.0,
                "target_price": 200.0,
                "trail": {"distance": 0.02},
            }
        ],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_ts_ms": 3 * TF,
                    "exit_price": 102.9,
                    "exit_reason": "trailing_stop",
                    "exit_fee": 0.1029,
                    "gross_pnl": 2.9,
                    "realized_pnl": 2.6971,
                    "hold_bars": 2,
                }
            ],
        },
    )

    # ================================================================== EXEC-020 ======
    # Break-even arms at +3% (103.00) and moves the stop to the entry. Bar 2 spans
    # 94..104: it both arms the break-even and takes the original 95 stop. Without
    # lower-timeframe evidence the adverse sequence applies, so the stop wins at 95.00
    # and break-even does not rescue the trade.
    #   realized = -5 - 0.1 - 0.095 = -5.195
    f["EXEC-020_break_even_cannot_rescue_same_bar"] = fixture(
        ["EXEC-020", "CAUS-005"],
        "Break-even activation cannot rescue a stop hit on the activating bar",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 104.0, 94.0, 95.0],
        ],
        signals=[
            {
                "ts_ms": 0,
                "side": 1,
                "stop_price": 95.0,
                "target_price": 200.0,
                "break_even": {"trigger_offset": 0.03, "stop_offset": 0.0},
            }
        ],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_price": 95.0,
                    "exit_reason": "stop",
                    "realized_pnl": -5.195,
                    "ambiguous": True,
                }
            ],
        },
    )

    # Bar 2 arms break-even cleanly (low 99, no stop touch); bar 3 then hits the moved
    # stop at the entry price of 100.00.
    #   exit fee = 100 * 0.001 = 0.1
    #   gross = 0.00, realized = 0 - 0.1 - 0.1 = -0.2
    f["EXEC-020_break_even_arms_then_fires"] = fixture(
        ["EXEC-020"],
        "Break-even arms on a clean bar and the moved stop fires on a later bar",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 104.0, 99.0, 103.0],
            [3 * TF, 103.0, 103.0, 99.0, 99.5],
        ],
        signals=[
            {
                "ts_ms": 0,
                "side": 1,
                "stop_price": 95.0,
                "target_price": 200.0,
                "break_even": {"trigger_offset": 0.03, "stop_offset": 0.0},
            }
        ],
        expect={
            "n_trades": 1,
            "trades": [
                {
                    "exit_ts_ms": 3 * TF,
                    "exit_price": 100.0,
                    "exit_reason": "break_even_stop",
                    "gross_pnl": 0.0,
                    "realized_pnl": -0.2,
                }
            ],
        },
    )

    # ================================================================== FUND-001 ======
    # Positive rate: the long pays. Settlement at 120000, mark = bar 2's open = 100.00.
    #   cashflow = -1 * 1 * 100 * 0.001 = -0.10
    # Exit by max hold at bar 3's open of 100.00: gross 0, fees 0.1 + 0.1 = 0.2.
    #   realized = 0 - 0.2 - 0.10 = -0.30
    f["FUND-001_long_pays_positive_rate"] = fixture(
        ["FUND-001", "FUND-004", "FUND-006"],
        "A positive funding rate is paid by the long, once, on the mark at settlement",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 100.0, 100.0, 100.0],
            [3 * TF, 100.0, 100.0, 100.0, 100.0],
        ],
        signals=[LONG_95_110],
        sim={"max_hold_bars": 2},
        funding=[[2 * TF, 0.001]],
        expect={
            "n_trades": 1,
            "trades": [{"funding": -0.1, "fees": 0.2, "realized_pnl": -0.3}],
            "n_funding_charges": 1,
        },
    )

    # Mirror: the short receives the same 0.10.
    #   realized = 0 - 0.2 + 0.10 = -0.10
    f["FUND-001_short_receives_positive_rate"] = fixture(
        ["FUND-001"],
        "A positive funding rate is received by the short",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 100.0, 100.0, 100.0],
            [3 * TF, 100.0, 100.0, 100.0, 100.0],
        ],
        signals=[{"ts_ms": 0, "side": -1, "stop_price": 105.0, "target_price": 90.0}],
        sim={"max_hold_bars": 2},
        funding=[[2 * TF, 0.001]],
        expect={
            "n_trades": 1,
            "trades": [{"side": -1, "funding": 0.1, "realized_pnl": -0.1}],
        },
    )

    # ================================================================== FUND-002 ======
    # Negative rate reverses the cashflow: the long receives 0.10.
    #   realized = 0 - 0.2 + 0.10 = -0.10
    f["FUND-002_negative_rate_reverses"] = fixture(
        ["FUND-002"],
        "A negative funding rate reverses the cashflow",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 100.0, 100.0, 100.0],
            [3 * TF, 100.0, 100.0, 100.0, 100.0],
        ],
        signals=[LONG_95_110],
        sim={"max_hold_bars": 2},
        funding=[[2 * TF, -0.001]],
        expect={
            "n_trades": 1,
            "trades": [{"funding": 0.1, "realized_pnl": -0.1}],
        },
    )

    # ================================================================== FUND-003 ======
    # Settlements at 0 (before the entry) and at 240000 (after the exit) are not charged.
    #   realized = 0 - 0.2 = -0.20 and there are no funding charges at all.
    f["FUND-003_no_funding_while_flat"] = fixture(
        ["FUND-003"],
        "No funding is charged while flat",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 100.0, 100.0, 100.0],
            [3 * TF, 100.0, 100.0, 100.0, 100.0],
            [4 * TF, 100.0, 100.0, 100.0, 100.0],
        ],
        signals=[LONG_95_110],
        sim={"max_hold_bars": 2},
        funding=[[0, 0.001], [4 * TF, 0.001]],
        expect={
            "n_trades": 1,
            "trades": [{"funding": 0.0, "realized_pnl": -0.2}],
            "n_funding_charges": 0,
        },
    )

    # ================================================================== FUND-004 ======
    # Two settlements inside the window, charged exactly once each.
    #   -0.10 at 120000 and -0.10 at 180000 -> funding total -0.20
    #   realized = 0 - 0.2 - 0.2 = -0.40
    f["FUND-004_each_settlement_once"] = fixture(
        ["FUND-004"],
        "Every settlement inside the window is charged exactly once",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.0, 100.0, 100.0],
            [2 * TF, 100.0, 100.0, 100.0, 100.0],
            [3 * TF, 100.0, 100.0, 100.0, 100.0],
            [4 * TF, 100.0, 100.0, 100.0, 100.0],
        ],
        signals=[LONG_95_110],
        sim={"max_hold_bars": 3},
        funding=[[2 * TF, 0.001], [3 * TF, 0.001]],
        expect={
            "n_trades": 1,
            "trades": [{"funding": -0.2, "realized_pnl": -0.4}],
            "n_funding_charges": 2,
        },
    )

    # ================================================================== QTY-001 ======
    # tick 0.1, step 0.01, entry slippage 0.0007 on an open of 100.00:
    #   raw fill = 100.07 -> nearest 0.1 tick = 100.10
    #   fixed notional 1000 -> raw qty = 1000 / 100.10 = 9.99000999... -> floor 0.01 = 9.99
    f["QTY-001_tick_and_step_rounding"] = fixture(
        ["QTY-001"],
        "Prices round onto the tick grid and quantities floor onto the quantity step",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 112.0, 99.0, 111.0],
        ],
        signals=[LONG_95_110],
        instrument={"tick_size": 0.1, "qty_step": 0.01, "min_qty": 0.01},
        costs={"entry_slippage": 0.0007},
        sizing={"mode": "fixed_notional", "fixed_notional": 1000.0},
        margin={"leverage": 2.0},
        expect={
            "n_trades": 1,
            "trades": [{"entry_price": 100.1, "qty": 9.99}],
        },
    )

    # ================================================================== QTY-002 ======
    # Minimum notional of 5000 against a requested 1000: skipped, not resized.
    f["QTY-002_below_min_notional_skips"] = fixture(
        ["QTY-002"],
        "An order below the minimum notional is skipped with a reason, never resized",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 112.0, 99.0, 111.0],
        ],
        signals=[LONG_95_110],
        instrument={"min_notional": 5000.0},
        sizing={"mode": "fixed_notional", "fixed_notional": 1000.0},
        expect={
            "n_trades": 0,
            "skip_counts": {"SKIP_BELOW_MIN_NOTIONAL": 1},
            "ending_equity": 10000.0,
        },
    )

    # Minimum quantity of 10 against a requested 1.0.
    f["QTY-002_below_min_qty_skips"] = fixture(
        ["QTY-002"],
        "An order below the minimum quantity is skipped with a reason",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 112.0, 99.0, 111.0],
        ],
        signals=[LONG_95_110],
        instrument={"min_qty": 10.0, "qty_step": 0.001},
        expect={"n_trades": 0, "skip_counts": {"SKIP_BELOW_MIN_QTY": 1}},
    )

    # ================================================================== QTY-003 ======
    # Minimum executable quantity is 1.0 and the stop is 5.00 away, so the smallest
    # possible order risks 5.00. The frozen cap is 0.001 * 1000 = 1.00. Skip, never
    # round up into over-risk.
    f["QTY-003_min_qty_exceeds_risk_cap"] = fixture(
        ["QTY-003"],
        "A minimum executable order that breaches the frozen risk cap is skipped",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 112.0, 99.0, 111.0],
        ],
        signals=[LONG_95_110],
        instrument={"min_qty": 1.0, "qty_step": 1.0},
        sizing={
            "mode": "risk_fraction",
            "risk_fraction": 0.001,
            "max_risk_fraction": 0.001,
        },
        sim={"starting_equity": 1000.0},
        expect={"n_trades": 0, "skip_counts": {"SKIP_MIN_QTY_RISK_CAP": 1}},
    )

    # ================================================================== QTY-004 ======
    # Initial margin at leverage 10 on a 100 notional is 10.00, but the wallet holds 5.00.
    f["QTY-004_insufficient_margin_rejects"] = fixture(
        ["QTY-004"],
        "Insufficient margin rejects the order instead of silently funding it",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 112.0, 99.0, 111.0],
        ],
        signals=[LONG_95_110],
        sim={"starting_equity": 5.0},
        expect={"n_trades": 0, "skip_counts": {"SKIP_INSUFFICIENT_MARGIN": 1}},
    )

    # ================================================================== QTY-010 ======
    # The stop at 90.00 sits beyond the 98.60 liquidation at leverage 50. With the
    # invariant enabled the order is rejected rather than simulated with a protective
    # level that could never protect anything.
    f["QTY-010_stop_beyond_liquidation_rejected"] = fixture(
        ["QTY-010"],
        "A stop beyond the liquidation price is rejected, not simulated",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 100.5, 89.0, 90.0],
            [2 * TF, 90.0, 91.0, 89.0, 90.0],
        ],
        signals=[{"ts_ms": 0, "side": 1, "stop_price": 90.0, "target_price": 110.0}],
        margin={"leverage": 50.0, "require_stop_inside_liquidation": True},
        expect={"n_trades": 0, "skip_counts": {"SKIP_STOP_INSIDE_LIQUIDATION": 1}},
    )

    # ================================================================== DATA-002 ======
    # Bar 2 claims a high of 99 below its open of 100. The engine refuses the series.
    f["DATA-002_ohlc_invariant_violation"] = fixture(
        ["DATA-002"],
        "A bar whose high is below its open is rejected",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [2 * TF, 100.0, 99.0, 98.0, 98.5],
        ],
        signals=[LONG_95_110],
        expect={"error": "OHLC"},
    )

    f["DATA-002_non_positive_price"] = fixture(
        ["DATA-002"],
        "A non-positive price is rejected",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 0.0, 100.0],
            [2 * TF, 100.0, 101.0, 99.0, 100.0],
        ],
        signals=[LONG_95_110],
        expect={"error": "positive"},
    )

    # ================================================================== DATA-001 ======
    f["DATA-001_duplicate_timestamp"] = fixture(
        ["DATA-001"],
        "A duplicate bar timestamp is rejected",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 99.0, 100.0],
            [TF, 100.0, 101.0, 99.0, 100.0],
        ],
        signals=[LONG_95_110],
        expect={"error": "increasing"},
    )

    f["DATA-001_out_of_order_timestamp"] = fixture(
        ["DATA-001"],
        "Out-of-order bars are rejected rather than silently sorted",
        bars=[
            QUIET_SIGNAL_BAR,
            [2 * TF, 100.0, 101.0, 99.0, 100.0],
            [TF, 100.0, 101.0, 99.0, 100.0],
        ],
        signals=[LONG_95_110],
        expect={"error": "increasing"},
    )

    # ================================================================== METR-007 ======
    # Three signals, all of which stop out on their own entry bar: an entry-bar exit rate
    # of 100%, far above the 25% threshold that must be reported prominently.
    f["METR-007_entry_bar_exit_rate_warning"] = fixture(
        ["METR-007"],
        "An entry-bar exit frequency above 25% raises a prominent warning",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 101.0, 94.0, 99.0],
            [2 * TF, 99.0, 100.0, 98.0, 100.0],
            [3 * TF, 100.0, 101.0, 94.0, 99.0],
            [4 * TF, 99.0, 100.0, 98.0, 100.0],
            [5 * TF, 100.0, 101.0, 94.0, 99.0],
            [6 * TF, 99.0, 100.0, 98.0, 99.0],
        ],
        signals=[
            {"ts_ms": 0, "side": 1, "stop_offset": 0.05, "target_offset": 0.10},
            {"ts_ms": 2 * TF, "side": 1, "stop_offset": 0.05, "target_offset": 0.10},
            {"ts_ms": 4 * TF, "side": 1, "stop_offset": 0.05, "target_offset": 0.10},
        ],
        expect={
            "n_trades": 3,
            "summary": {"entry_bar_exits": 3, "entry_bar_exit_rate": 1.0},
            "warns_contains": "entry bar",
        },
    )

    # ================================================================== PORT-001 ======
    # Two symbols on one wallet. AAAUSDT stops out on its entry bar for -5.195 and
    # BBBUSDT takes its target on its entry bar for +9.79.
    #   ending equity = 10000 - 5.195 + 9.79 = 10004.595
    f["PORT-001_shared_wallet_two_symbols"] = fixture(
        ["PORT-001", "PORT-002"],
        "Two symbols settle against one chronological shared wallet",
        kind="portfolio",
        bars=[],
        signals=[],
        expect={
            "n_trades": 2,
            "ending_equity": 10004.595,
            "trade_symbols": ["AAAUSDT", "BBBUSDT"],
        },
    )
    f["PORT-001_shared_wallet_two_symbols"]["symbols"] = {
        "AAAUSDT": {
            "instrument": {**INSTRUMENT, "symbol": "AAAUSDT"},
            "bars": {
                "timeframe_ms": TF,
                "rows": [
                    QUIET_SIGNAL_BAR,
                    [TF, 100.0, 101.0, 94.0, 99.0],
                    [2 * TF, 99.0, 100.0, 98.0, 99.0],
                ],
            },
            "signals": [{"ts_ms": 0, "side": 1, "stop_price": 95.0, "target_price": 110.0}],
        },
        "BBBUSDT": {
            "instrument": {**INSTRUMENT, "symbol": "BBBUSDT"},
            "bars": {
                "timeframe_ms": TF,
                "rows": [
                    QUIET_SIGNAL_BAR,
                    [TF, 100.0, 111.0, 99.0, 110.0],
                    [2 * TF, 110.0, 111.0, 109.0, 110.0],
                ],
            },
            "signals": [{"ts_ms": 0, "side": 1, "stop_price": 95.0, "target_price": 110.0}],
        },
    }

    # ================================================================== PORT-003 ======
    # The utilisation cap is lifted to 1.00 so the wallet itself, not the policy cap, is
    # the binding constraint and the skip reason isolates shared-margin exhaustion.
    # A 12.00 wallet at leverage 10 funds one 100-notional position (10.00 of initial
    # margin) and leaves 2.00 free, so the second symbol in chronological order is
    # rejected for insufficient margin rather than being silently sized down.
    f["PORT-003_shared_margin_rejects_second"] = fixture(
        ["PORT-003"],
        "Shared margin rejects the second simultaneous signal and records the skip",
        kind="portfolio",
        bars=[],
        signals=[],
        margin={"max_margin_utilisation": 1.0},
        sim={"starting_equity": 12.0},
        expect={
            "n_trades": 1,
            "trade_symbols": ["AAAUSDT"],
            "skip_counts": {"SKIP_INSUFFICIENT_MARGIN": 1},
        },
    )
    f["PORT-003_shared_margin_rejects_second"]["symbols"] = {
        # AAAUSDT deliberately touches neither its stop nor its target, so it still holds
        # the wallet's margin when BBBUSDT's entry is attempted on the same bar. Letting
        # it exit intrabar would free the margin and make the contention unobservable.
        "AAAUSDT": {
            "instrument": {**INSTRUMENT, "symbol": "AAAUSDT"},
            "bars": {
                "timeframe_ms": TF,
                "rows": [
                    QUIET_SIGNAL_BAR,
                    [TF, 100.0, 101.0, 99.0, 100.0],
                    [2 * TF, 100.0, 101.0, 99.0, 100.0],
                ],
            },
            "signals": [{"ts_ms": 0, "side": 1, "stop_price": 95.0, "target_price": 110.0}],
        },
        "BBBUSDT": {
            "instrument": {**INSTRUMENT, "symbol": "BBBUSDT"},
            "bars": {
                "timeframe_ms": TF,
                "rows": [
                    QUIET_SIGNAL_BAR,
                    [TF, 100.0, 111.0, 99.0, 110.0],
                    [2 * TF, 110.0, 111.0, 109.0, 110.0],
                ],
            },
            "signals": [{"ts_ms": 0, "side": 1, "stop_price": 95.0, "target_price": 110.0}],
        },
    }

    # ================================================================== QTY-008 ======
    # Wallet reconciliation across a mixed run: one winner, one loser, funding on both.
    f["QTY-008_wallet_reconciles"] = fixture(
        ["QTY-008"],
        "starting equity + gross PnL - fees +/- funding == ending equity",
        bars=[
            QUIET_SIGNAL_BAR,
            [TF, 100.0, 111.0, 99.0, 110.0],
            [2 * TF, 110.0, 111.0, 109.0, 110.0],
            [3 * TF, 110.0, 111.0, 103.0, 104.0],
            [4 * TF, 104.0, 105.0, 103.0, 104.0],
        ],
        signals=[
            {"ts_ms": 0, "side": 1, "stop_price": 95.0, "target_price": 110.0},
            {"ts_ms": 2 * TF, "side": 1, "stop_price": 104.5, "target_price": 130.0},
        ],
        funding=[[3 * TF, 0.001]],
        expect={"reconciles": True, "n_trades": 2},
    )

    f.update(_metric_fixtures())
    return f


def metric_fixture(
    ids: list[str], title: str, inputs: dict[str, Any], expect: dict[str, Any]
) -> dict[str, Any]:
    """A metric graded on its own arithmetic, with no simulation in the way."""
    return {
        "ids": ids,
        "kind": "metrics",
        "title": title,
        "rationale": "",
        **inputs,
        "expect": {"metrics": expect},
        "tolerance": 1e-9,
    }


def _metric_fixtures() -> dict[str, dict[str, Any]]:
    f: dict[str, dict[str, Any]] = {}

    # ================================================================== METR-001 ======
    # Fold A is +10 against -5 (ratio 2.00); fold B is +1 against -10 (ratio 0.10). The
    # mean of the ratios is 1.05 and reads as profitable. Pooled: 11 / 15 = 0.733333...
    f["METR-001_profit_factor_is_pooled"] = metric_fixture(
        ["METR-001"],
        "Profit factor pools the trades instead of averaging the folds",
        {"pnls": [10.0, -5.0, 1.0, -10.0]},
        {
            "profit_factor": 11.0 / 15.0,
            "profit_factor_note": "",
            # 2 wins in 4 = 50%, Wilson 95%: 0.150,  0.850  (symmetric at p = 0.5)
            "win_rate": 0.5,
        },
    )

    # An uncapped ratio: 1000 / 0.01 = 100000. No sentinel ceiling.
    f["METR-001_profit_factor_is_uncapped"] = metric_fixture(
        ["METR-001"],
        "A large profit factor is reported, not clipped to a tidy ceiling",
        {"pnls": [1000.0, -0.01]},
        {"profit_factor": 100_000.0},
    )

    # ================================================================== METR-002 ======
    # Wilson score interval for 3 wins in 3, z = 1.96, written out from the formula:
    #   centre = (phat + z^2/2n) / (1 + z^2/n)
    #   margin = (z / (1 + z^2/n)) * sqrt(phat(1-phat)/n + z^2/4n^2)
    z, wins, trials = 1.96, 3, 3
    phat = wins / trials
    denom = 1.0 + z * z / trials
    centre = (phat + z * z / (2 * trials)) / denom
    margin = (z / denom) * (
        (phat * (1.0 - phat) / trials + z * z / (4 * trials * trials)) ** 0.5
    )
    f["METR-002_zero_gross_loss_is_infinite"] = metric_fixture(
        ["METR-002"],
        "Zero gross loss is infinity with a sample warning, never an automatic pass",
        {"pnls": [1.0, 2.0, 3.0]},
        {
            "profit_factor": "inf",
            "profit_factor_note": "insufficient-sample warning",
            "win_rate": 1.0,
            # Three winners do not establish a 100% win rate: the 95% interval starts
            # below 0.44, which is the whole reason a bare win rate is never quotable.
            "win_rate_ci_low": max(0.0, centre - margin),
            "win_rate_ci_high": min(1.0, centre + margin),
        },
    )

    # ================================================================== METR-003 ======
    # Peak 120 to trough 90 is 30, which is 25% of the peak, and the curve spends two
    # observations below the peak before recovering.
    f["METR-003_drawdown_on_the_equity_curve"] = metric_fixture(
        ["METR-003"],
        "Drawdown is measured peak to trough on the mark-to-market curve",
        {"equity": [100.0, 120.0, 90.0, 95.0, 130.0]},
        {"max_drawdown": 30.0, "max_drawdown_pct": 0.25, "max_drawdown_periods": 2},
    )

    # ================================================================== METR-004 ======
    # r = [0.01, -0.01, 0.02, 0.00]
    #   mean = 0.005
    #   deviations       = [0.005, -0.015, 0.015, -0.005]
    #   sum of squares   = 2.5e-05 + 2.25e-04 + 2.25e-04 + 2.5e-05 = 5.0e-04
    #   sample variance  = 5.0e-04 / 3 = 1.6666666666666666e-04
    #   sample std       = 0.012909944487358056
    #   raw Sharpe       = 0.005 / 0.012909944487358056 = 0.3872983346207417
    #   annualised       = raw * sqrt(365) = 0.3872983346207417 * 19.10497317454279
    #                    = 7.399338... (see the literal below)
    RAW_SHARPE = 0.005 / ((5.0e-04 / 3.0) ** 0.5)
    f["METR-004_raw_and_annualised_sharpe"] = metric_fixture(
        ["METR-004"],
        "Raw periodic and annualised Sharpe are separate numbers with a stated factor",
        {"returns": [0.01, -0.01, 0.02, 0.0], "annualisation_days": 365.0},
        {
            "sharpe.raw_periodic": RAW_SHARPE,
            "sharpe.annualisation_factor": 365.0**0.5,
            "sharpe.annualised": RAW_SHARPE * (365.0**0.5),
            "sharpe.n_periods": 4,
            "sharpe.available": True,
        },
    )

    f["METR-004_sharpe_undefined_on_a_flat_curve"] = metric_fixture(
        ["METR-004"],
        "Zero dispersion makes Sharpe undefined, not infinite and not zero",
        {"returns": [0.01, 0.01, 0.01]},
        {
            "sharpe.raw_periodic": "nan",
            "sharpe.available": False,
            "sharpe.reason": "zero return dispersion",
        },
    )

    # ================================================================== METR-005 ======
    # Bartlett-kernel long-run variance at truncation lag L = max(1, floor(4*(n/100)^(2/9))).
    # For n = 12: (0.12)^(2/9) = 0.62428..., 4 * that = 2.497..., so L = 2.
    #
    #   gamma_k = (1/n) * sum_t (x_t - xbar)(x_{t+k} - xbar)
    #   lrv     = gamma_0 + 2 * sum_{k=1..L} (1 - k/(L+1)) * gamma_k
    #   HAC Sharpe = mean / sqrt(lrv)
    #
    # The series below is deliberately positively autocorrelated (three up, three down,
    # repeating), so the long-run variance exceeds gamma_0 and the HAC value is BELOW the
    # IID one. The expected numbers are computed here from that formula directly, not by
    # calling the engine.
    series = [0.02, 0.015, 0.01, -0.01, -0.015, -0.005, 0.02, 0.018, 0.012, -0.012, -0.014, -0.006]
    n = len(series)
    mean = sum(series) / n
    dev = [x - mean for x in series]
    gamma0 = sum(d * d for d in dev) / n
    lag = 2
    lrv = gamma0
    for k in range(1, lag + 1):
        weight = 1.0 - k / (lag + 1.0)
        gamma_k = sum(dev[t] * dev[t - k] for t in range(k, n)) / n
        lrv += 2.0 * weight * gamma_k
    variance = sum(d * d for d in dev) / (n - 1)
    f["METR-005_hac_sharpe_alongside_iid"] = metric_fixture(
        ["METR-005"],
        "A serial-dependence-aware Sharpe is reported next to the IID value",
        {"returns": series, "annualisation_days": 365.0},
        {
            "sharpe.hac_lag": lag,
            "sharpe.raw_periodic": mean / (variance**0.5),
            "sharpe.hac_raw": mean / (lrv**0.5),
            "sharpe.hac_annualised": (mean / (lrv**0.5)) * (365.0**0.5),
        },
    )

    return f


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for existing in OUT_DIR.glob("*.json"):
        existing.unlink()
    fixtures = build()
    for name, payload in sorted(fixtures.items()):
        path = OUT_DIR / f"{name}.json"
        path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    print(f"wrote {len(fixtures)} fixtures to {OUT_DIR}")


if __name__ == "__main__":
    main()
